// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbTSpSti9gaWHY776pRSQ5RMhqt02FwD0',
    appId: '1:552137544101:web:ee5526c4db6da7beac984c',
    messagingSenderId: '552137544101',
    projectId: 'portfolio-99820',
    authDomain: 'portfolio-99820.firebaseapp.com',
    storageBucket: 'portfolio-99820.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWCJmMcWORiuzxrDIAYUBguk6gwjJpxs4',
    appId: '1:552137544101:android:b5feb7b2436dff32ac984c',
    messagingSenderId: '552137544101',
    projectId: 'portfolio-99820',
    storageBucket: 'portfolio-99820.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADmg1gJc6ud1iuXcPZgpqtIpSb3O_qLvY',
    appId: '1:552137544101:ios:c981245e638a5095ac984c',
    messagingSenderId: '552137544101',
    projectId: 'portfolio-99820',
    storageBucket: 'portfolio-99820.appspot.com',
    iosClientId: '552137544101-vota8tqofq6u8s49pfqgso9qjgev96n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );
}
